//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class BaseUpgradeObject
		{
				int tierLevel;
				string upgradeName;
				int ironCost;
				int copperCost;
				int alumCost;
				int diamondCost;
				int uranCost;
				int hydrogenCost;
				int platCost;
				int leadCost;
				int goldCost;
				int unobtainCost;
				
				
				public BaseUpgradeObject (int tierLevel, string upgradeName, int ironCost, int copperCost, int alumCost, int diamondCost, 
					int uranCost, int hydrogenCost, int platCost, int leadCost, int goldCost, int unobtainCost)
				{
					this.tierLevel = tierLevel;
					this.upgradeName = upgradeName;
					this.ironCost = ironCost;
					this.copperCost = copperCost;
					this.alumCost = alumCost;
					this.diamondCost = diamondCost;
					this.uranCost = uranCost;
					this.hydrogenCost = hydrogenCost;
					this.platCost = platCost;
					this.leadCost = leadCost;
					this.goldCost = goldCost;
					this.unobtainCost = unobtainCost;
				}
		}
}

