//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Xml; 
using System.Xml.Serialization; 
using System.IO; 
using System.Text;
using UnityEngine;
using UnityEditor;
namespace AssemblyCSharp
{
		public class PlayerSaveObject
		{
				public int playerHealth;
				public ArrayList listOfPurchasedShipUpgrades;
				public int[] listOfResourcesCollected;
				public ArrayList listOfPurchasedHomeBaseUpgrades;
				
				/// <summary>
				/// Initializes a new instance of the <see cref="AssemblyCSharp.PlayerSaveObject"/> class.
				/// </summary>
				public PlayerSaveObject(){
				
				}
				
				/// <summary>
				/// Initializes a new instance of the <see cref="AssemblyCSharp.PlayerSaveObject"/> class.
				/// </summary>
				/// <param name="saveTimeStamp">Save time stamp.</param>
				/// <param name="playerHealth">Player health.</param>
				/// <param name="listOfPurchasedShipUpgrades">List of purchased ship upgrades.</param>
				/// <param name="listOfResourcesCollected">List of resources collected.</param>
				/// <param name="listOfPurchasedHomeBaseUpgrades">List of purchased home base upgrades.</param>
				public PlayerSaveObject (int playerHealth, ArrayList listOfPurchasedShipUpgrades, int[] listOfResourcesCollected, ArrayList listOfPurchasedHomeBaseUpgrades)
				{
						this.playerHealth = playerHealth;
						this.listOfPurchasedShipUpgrades = listOfPurchasedShipUpgrades;
						this.listOfResourcesCollected = listOfResourcesCollected;
						this.listOfPurchasedHomeBaseUpgrades = listOfPurchasedHomeBaseUpgrades;
				}
				
				
				/// <summary>
				/// Writes the save object to a file.
				/// </summary>
				/// <param name="playerSaveObject">Player save object.</param>
				public bool saveTheGame (PlayerSaveObject playerSaveObject)
				{

						string purchasedShipUpgrades = "";
						string purchasedHomeBaseupgrades = "";
						string resourcesCollected = "";
						int counter = 0;
						foreach (string item in playerSaveObject.listOfPurchasedShipUpgrades) {
								if (counter == playerSaveObject.listOfResourcesCollected.Length - 1) {
										purchasedShipUpgrades += String.Format ("{0}", item);
										counter = 0;
								} else {
										purchasedShipUpgrades += String.Format ("{0},", item);
								}
						}
						foreach (string item in playerSaveObject.listOfPurchasedHomeBaseUpgrades) {
								if (counter == playerSaveObject.listOfResourcesCollected.Length - 1) {
										purchasedHomeBaseupgrades += String.Format ("{0}", item);
										counter = 0;
								} else {
										purchasedHomeBaseupgrades += String.Format ("{0},", item);
								}
						}
						foreach (int item in playerSaveObject.listOfResourcesCollected) {
								if (counter == playerSaveObject.listOfResourcesCollected.Length - 1) {
										resourcesCollected += String.Format ("{0}", item);
										counter = 0;
								} else {
										resourcesCollected += String.Format ("{0},", item);
								}
								
								counter++;
						}
                              
						PlayerPrefs.SetInt ("health", playerSaveObject.playerHealth);
						PlayerPrefs.SetString ("shipUpgrades", purchasedShipUpgrades);
						PlayerPrefs.SetString ("homeBaseUpgrades", purchasedHomeBaseupgrades);
						PlayerPrefs.SetString ("resourcesCollected", resourcesCollected);
						PlayerPrefs.Save ();
						
						if(PlayerPrefs.GetInt("health") > 0 && 
						!PlayerPrefs.GetString("shipUpgrades").Equals("") &&
			   			!PlayerPrefs.GetString("homeBaseUpgrades").Equals("") &&
			   			!PlayerPrefs.GetString("resourcesCollected").Equals("")){
			   				return true;
			   			}else{
			   				return false;
			   			}
				}
				
				
				/// <summary>
				/// Reads the save file.
				/// </summary>
				/// <param name="saveFileName">Save file name.</param>
				public PlayerSaveObject loadTheGame ()
				{
						int health = PlayerPrefs.GetInt ("health");
						string shipUpgrades = PlayerPrefs.GetString ("shipUpgrades");
						string homeBaseUpgrades = PlayerPrefs.GetString ("homeBaseUpgrades");
						string resourcesCollected = PlayerPrefs.GetString ("resourcesCollected");
					
						string[] listOfShipUpgrades = shipUpgrades.Split (',');
						string[] listOfHomeBaseUpgrades = homeBaseUpgrades.Split (',');
						string[] listOfResourcesCollected = resourcesCollected.Split (',');
						
						int[] resources = new int[11];
						for(int i = 0; i < listOfResourcesCollected.Length; i++){
							resources[i] = int.Parse(listOfResourcesCollected[i]);
						}
						

						ArrayList arrayListOfshipUpgrades = new ArrayList(listOfShipUpgrades);
						ArrayList arrayListOfHomeBaseUpgrades = new ArrayList(listOfHomeBaseUpgrades);
				
				
						//parse the save file
			PlayerSaveObject playerSave = new PlayerSaveObject (health, arrayListOfshipUpgrades, resources, arrayListOfHomeBaseUpgrades);
					
						return playerSave;
				}
		}
}

