//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Xml; 
using System.Xml.Serialization; 
using System.IO; 
using System.Text;
using UnityEngine;
namespace AssemblyCSharp
{
		public class PlayerSaveObject
		{
				string saveTimeStamp;
				int playerHealth;
				ArrayList listOfPurchasedShipUpgrades;
				int[] listOfResourcesCollected;
				ArrayList listOfPurchasedHomeBaseUpgrades;
			
				public PlayerSaveObject (string saveTimeStamp, int playerHealth, ArrayList listOfPurchasedShipUpgrades, int[] listOfResourcesCollected, ArrayList listOfPurchasedHomeBaseUpgrades)
				{
						this.saveTimeStamp = saveTimeStamp;
						this.playerHealth = playerHealth;
						this.listOfPurchasedShipUpgrades = listOfPurchasedShipUpgrades;
						this.listOfResourcesCollected = listOfResourcesCollected;
						this.listOfPurchasedHomeBaseUpgrades = listOfPurchasedHomeBaseUpgrades;
				}
				
				
				/// <summary>
				/// Writes the save object to a file.
				/// </summary>
				/// <param name="playerSaveObject">Player save object.</param>
				public bool writeSaveObjectToFile (PlayerSaveObject playerSaveObject)
				{
						
						string purchasedShipUpgrades = "";
						string purchasedHomeBaseupgrades = "";
						string resourcesCollected = "";
						foreach (string item in playerSaveObject.listOfPurchasedShipUpgrades) {
								purchasedShipUpgrades += String.Format ("{0},", item);
						}
						foreach (string item in playerSaveObject.listOfPurchasedHomeBaseUpgrades) {
								purchasedHomeBaseupgrades += String.Format ("{0},", item);
						}
						foreach (int item in playerSaveObject.listOfResourcesCollected) {
								resourcesCollected += String.Format ("{0},", item);
						}
	
						string playerSaveFormat = String.Format ("Health:{0}|purchasedShipUpgrades:{1}|purchasedHomeBaseupgrades{2}|resourcesCollected:{3}",
                              playerSaveObject.playerHealth, purchasedShipUpgrades, purchasedHomeBaseupgrades, resourcesCollected);
                              
						string fileName = "Saves/" + playerSaveObject.saveTimeStamp + ".txt";
						if (File.Exists (fileName)) {
								Debug.Log (fileName + " already exists.");
								return false;
						} else {
								
								var sr = File.CreateText (fileName);
								sr.WriteLine (playerSaveFormat);
								Debug.Log ("The save file has been written!");
								sr.Close ();
								readSaveFile(fileName);
								return true;
						}
			
				}
				
				/// <summary>
				/// Reads the save files.
				/// </summary>
				/// <returns>The save files.</returns>
				public ArrayList readSaveFiles(){
					ArrayList listOfSaveFiles = new ArrayList();
					
					return listOfSaveFiles;
				
				}
				
				
				public void readSaveFile(String saveFileName){
					//parse the save file
					PlayerSaveObject playerSave;
					if(File.Exists(saveFileName)){
						var sr = File.OpenText(saveFileName);
						var line = sr.ReadLine();
						while(line != null){
					//Health:10,purchasedShipUpgrades:,purchasedHomeBaseupgrades,resourcesCollected:00000000000
					string [] split = line.Split(new Char [] {'|'});
							Debug.Log(line); // prints each line of the file
							line = sr.ReadLine();
						}  
					} else {
						Debug.Log("Could not Open the file: " + saveFileName + " for reading.");
						return;
					}
					//return playerSave;
				
				}
		}
}

